config/routes.rb
Rails.application.routes.draw do

resources :posts do
  collection do
    get '/newest' => 'posts#newest', as: :newest
    get '/oldest' => 'posts#oldest', as: :oldest
    get '/best' => 'posts#best', as: :best
    get '/worst' => 'posts#worst', as: :worst
  end
  resources :comments
    resources :tags
    get '/up-vote' => 'votes#up_vote', as: :up_vote
    get '/down-vote' => 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
end

resources :catagories

resources :relationships, only: [:create, :destroy]

  devise_for :users
  resources :users, only: [:show, :index, :update] do
      member do
        get :following, :followers
      end
  end

  get 'home' => 'welcome#index'

  root to: 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  default_scope { order('updated_at DESC') }

  validates :body, length: { minimum: 1, maximum: 300 }, presence: true
  validates :post, presence: true
  validates :user, presence: true

after_create :send_favorite_emails

  private

  def send_favorite_emails
    self.post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, self.post, self).deliver
    end
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index
    @post = Post.find(params[:post_id])
    @comments = @post.comments.paginate(page: params[:page], per_page: 20)
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
    authorize @comment
  end

  def create
    @comment = current_user.comments.build( comment_params )
    @comment.post = Post.find(params[:post_id])
    @new_comment = Comment.new

    authorize @comment 

    if @comment.save
      flash[:notice] = "Bam!"
    else
      flash[:error] = "What was that?! Maybe too many or too few characters. Try again."
    end
        redirect_to post_comments_path 
  end

  def edit
    @comment.post = Post.find(params[:post_id])
    #@comment = Comment.find(params[:id])
    authorize @comment
  end

  def update
    @comment = Comment.find(params[:id])
    authorize @comment
    if @comment.update_attributes(comment_params)
      redirect_to post_comments_path

    # elsif editing from user show view, redirect_to back
    
    else
      flash[:error] = "Try again"
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    body = @comment.body

    authorize @comment
    if @comment.destroy
      flash[:notice] = "collab-o-qwap all gone."
      redirect_to post_comments_path
    else
      flash[:error] = "There was an error."
      redirect_to post_comments_path
      #render :index
    end
  end


  private

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<h3>Edit collab-o-qwap:</h3>

<%= form_for @comment do |f| %>
  <div>
    <%= f.text_area :body, placeholder: "Edit your collab-o-qwap here." %>
  </div>

  <div>
    <%= f.submit "Post collab-o-qwap", class: "basic ui button" %>
  </div>
<% end %>

app/views/comments/index.html.erb
<%#= content_tag :div, class: 'media', id: "comment-#{comment.id}" do %>

<h6>collab-o-qwap regarding:</h6>
<div class="collab header">

  <div class="ui grid">
     <div class="row">
        <div class="fourteen wide column">
          <div class="segment">
            <div class="qwap list">
              
              <h5><%= @post.body %><br>( <span><em><%= link_to @post.user.name, @post.user if @post.user %>,<%= time_ago_in_words(@post.created_at) %> ago) </em></h5>
              <% if policy(Comment.new).create? %>
                <%= link_to "New collab-o-qwap", new_post_comment_path, class: "basic ui button" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<div class="page">
<%= will_paginate @comments %>
</div>



  
<% @comments.each do |comment| %>
<div class="collab list">
  <div class="ui grid">
   <div class="row">
      <div class="fourteen wide column">
        <div class="segment">
          <div class="qwap list">
            <h5><%= comment.body %> <br>( <span><em><%= link_to comment.user.name, comment.user if comment.user %>,<%= time_ago_in_words(comment.created_at) %> ago, </em></span> )</h5>



            <% if false %>
            <% if policy(comment).update? %>
              <%= link_to "Edit", edit_post_comment_path(@post, comment), class: "basic ui button" %>
            <% end %>  
            <% end %>



            <% if policy(comment).destroy? %>
              <%= link_to "Vaporize!", [@post, comment], method: :delete, data: { confirm: 'Final answer? Cause this topic is about to be real gone.'}, class: "basic ui button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>



<div class="page">
<%= will_paginate @comments %>
</div>
<%# end %>

app/views/comments/new.html.erb
<h3>New collab-o-qwap:</h3>

<%= form_for [@post, @comment] do |f| %>
  <div class="new collab area">
    <%= f.text_area :body, placeholder: "Begin collab-o-qwapping here. Remember, we all enter into this qwap-o-shpere knowing these are all qwappy ideas so PLEASE do not criticize any qwaps. This is about positive and constructive collaboration." %>
  </div>

  <div>
    <%= f.submit "Post collab-o-qwap", class: "basic ui button" %>
  </div>
<% end %>