config/routes.rb
Rails.application.routes.draw do

resources :posts do
  collection do
    get '/newest' => 'posts#newest', as: :newest
    get '/oldest' => 'posts#oldest', as: :oldest
    get '/best' => 'posts#best', as: :best
    get '/worst' => 'posts#worst', as: :worst
  end
  resources :comments
    resources :tags
    get '/up-vote' => 'votes#up_vote', as: :up_vote
    get '/down-vote' => 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
end

resources :catagories

resources :relationships, only: [:create, :destroy]

  devise_for :users
  resources :users, only: [:show, :index, :update] do
      member do
        get :following, :followers
      end
  end

  get 'home' => 'welcome#index'

  root to: 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/post.rb
class Post < ActiveRecord::Base
  #has_many :tags, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  # belongs_to :catagory

  after_create :send_followers_email

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  def points
    self.votes.sum(:value).to_i
  end

  def update_rank
    #age = (self.created_at - Time.new(1970,1,1)) / 86400
    new_rank = points #+ age

    self.update_attribute(:rank, new_rank)
  end

  validates :body, length: { minimum: 1, maximum: 200 }, presence: true
  validates :user, presence: true

  private 

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  #def send_email_followers
    # grab the creator of the post (post.user)
    #@post.user =  
    # see if they have any followers
    # if so, send an email to each follower
  #end

  def send_followers_email
    relationships = Relationship.where(followed_id: self.user.id)
    relationships.each do |relationship|
      FollowMailer.new_post(relationship.follower, self).deliver
    end
  end

# When someone votes in the top 25 index view the qwap only earns 1/4 pt
#def create_top_vote
  #user.votes.create(value: 0.25, post: self)
#end

# When someone votes in the random qwap mode, the qwap earns 2pts
#def create_random_vote
  #user.votes.create(value: 2, post: self)
#end

# When someone votes in the member qwap view, the qwap earns 1/2 pt
#def create_member_vote
  #user.votes.create(value: 0.5, post: self)
#end

# Users get points for voting

# Users can only vote 10 times per 24hrs (?)

# When someone votes in the top 25 index view the user earns 1/4 pt
#def create_top_vote
  #user.votes.create(value: 0.25, user: self)
#end

# When someone votes in the random qwap mode, the user earns 2pts
#def create_random_vote
  #user.votes.create(value: 2, user: self)
#end

# When someone votes in the member qwap view, the user earns 1/2 pt
#def create_member_vote
  #user.votes.create(value: 0.5, user: self)
#end








end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user).order('created_at DESC').paginate(page: params[:page], per_page: 20)
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
  @post = current_user.posts.build(post_params)
  @new_post = Post.new
  authorize @post
    if @post.save
      flash[:notice] = "Post was saved."
      redirect_to posts_path
    else
      flash[:error] = "Error! That was either way too short or over 200 characters."
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    authorize @post
  end

  def update
    @post = Post.find(params[:id])
    authorize @post
    if @post.update_attributes(post_params)
      redirect_to posts_path

    # elsif editing from user show view, redirect_to back
    
    else
      flash[:error] = "Try again"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    body = @post.body

    authorize @post
    if @post.destroy
      flash[:notice] = "qwap all gone."
      redirect_to posts_path
    else
      flash[:error] = "There was an error."
      redirect_to posts_path
      #render :index
    end
  end

  def oldest
    @posts = Post.order('created_at ASC').paginate(page: params[:page], per_page: 20)
    render :index
  end

  def newest
    @posts = Post.order('created_at DESC').paginate(page: params[:page], per_page: 20)
    render :index
  end

  def best
    @posts = Post.order('rank DESC').paginate(page: params[:page], per_page: 20)
    render :index
  end

  def worst
    @posts = Post.order('rank ASC').paginate(page: params[:page], per_page: 20)
    render :index
  end

  #def random
  #  @post = Post.rand 
  #  render :show
  #end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<h3>Fix qwap:</h3>

<%= form_for @post do |f| %>
  <div>
    <%= f.text_area :body, placeholder: "Edit your qwap here. And REMEMBER, 200 characters or less." %>
  </div>

  <div>
    <%= f.submit "Done editing your qwap?", class: "basic ui button" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<h3>list of all the qwap:</h3>

<div class="page">
<%= will_paginate @posts %>
</div>

<% if policy(Post.new).create? %>
<%= link_to "add more qwap!", new_post_path, class: "basic ui button" %>
<% else%>
<%= link_to "add more qwap!", new_user_session_path, class: "basic ui button" %>
<% end %>

<%= link_to "newest", newest_posts_path, class: "basic ui button" %>

<%= link_to "oldest", oldest_posts_path, class: "basic ui button" %>

<%= link_to "best", best_posts_path, class: "basic ui button" %>

<%= link_to "worst", worst_posts_path, class: "basic ui button" %>

<%#= link_to "random", post_comments_path(@post), class: "basic ui button" %>
  
<% @posts.each do |post| %>
  <div class="ui grid">
   <div class="row">
      <div class="column">
        <div class="segment">
          <div class="votes">
            <%= render partial: 'votes/voter', locals: { post: post } %>
          </div>
        </div>
      </div>
      <div class="fourteen wide column">
        <div class="segment">
          <div class="qwap list">

            <% if false %><h5><%= post.body %> <br>
              ( <span><em><%= link_to post.user.name, post.user if post.user %>, <%= time_ago_in_words(post.created_at) %> ago, </em>[<%= pluralize(post.up_votes, 'up vote') %>/<%= pluralize(post.down_votes, 'down vote') %>]</span> )<br>
              <span></p><%= render partial: 'favorites/favorite', locals: { post: post } %></p></span><a href="https://twitter.com/share" class="basic ui button" data-lang="en">Tweet</a></h5>
            <% end %>

              <h5><%= post.body %>
              <div class="post user name">
                <%= link_to post.user.name, post.user if post.user %>, <%= time_ago_in_words(post.created_at) %> ago,
              </div>
              <div class="votes total">
                [<%= pluralize(post.up_votes, 'up vote') %>/<%= pluralize(post.down_votes, 'down vote') %>]
              </div>

              
              <div class="fav">
                <%= render partial: 'favorites/favorite', locals: { post: post } %>
              </div>

              <% if current_user %>
              <div class="tweet">
                <a href="https://twitter.com/share" class="basic ui button" data-lang="en">Tweet</a>
              </div>

              <% else %>

              <div class="tweet pull left">
                <a href="https://twitter.com/share" class="basic ui button" data-lang="en">Tweet</a>
              </div>
              <% end %>

              </h5>

              

              <% if false %>
              Previous layout option
              <div class="comment count">
                <%= pluralize post.comments.count, 'comment' %>
              </div>
              <% end %>

              <% if false %>
              <% if policy(post).update? %>
              <div class="edit">
              <%= link_to edit_post_path(post), class: "basic ui icon" do %>
              <i class="pencil icon"></i>
              <% end %>
              </div>
            <% end %>  


            <% if policy(post).destroy? %>
            <div class="delete">
              <%= link_to post, method: :delete, data: { confirm: 'Final answer? Cause this qwap is about to be real gone.'}, class: "basic ui icon" do %>
                  <i class="remove icon"></i>
                  <% end %>
                </div>
            <% end %>
            <% end %>

             

            <%= link_to post_comments_path(post), class: 'basic ui button' do %>  
            <%= pluralize post.comments.count, 'collab-o-qwap/comment' %>
            <% end %>

            

            <%# Should use ajax to add qwap tags without refresh
            <%= link_to 'tag qwap(coming soon)', posts_path, class: 'basic ui button' %>
          

            <% if policy(post).update? %>
            <%= link_to 'edit qwap', edit_post_path(post), class: 'basic ui button' %>
            <% end %>



            <% if false %> If qwap is already asigned a type the button will be labeled that type
            <%= link_to 'qwap type? (coming soon)', posts_path, class: 'basic ui button' %>
            <% end %>


            <% if policy(post).destroy? %>
            <%= link_to 'vaporize qwap!', post, method: :delete, data: { confirm: 'Final answer? Cause this qwap is about to be real gone.'}, class: 'basic ui button' %>
            <% end %>
            




          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>



<div class="page">
<%= will_paginate @posts %>
</div>

<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>

app/views/posts/new.html.erb
<h3>How to qwap:</h3>
<ol>
  <li>Add new qwap.(keep it PG please)</li>
  <li>200 character limit!</li>
  <li>Save that qwap!</li>
</ol>

<h3>New qwap</h3>

<%= form_for @post do |f| %>
  <div class="new qwap">
    <%= f.text_area :body, placeholder: "Enter your qwap here. 200 characters or fewer FYI" %>
      <span><%= f.submit "Save", class: "ui red button" %></span>
  </div>


  <% if false %>
  <div class="tag btn">
    <%= link_to "Tag qwap (coming soon)", posts_path, class: "basic ui button" %>
    <span class="type btn"><%= link_to "Type?", posts_path, class: "basic ui button" %></span>
  </div>
  <% end %>




  <% if false %>
    </div class="tag field">
      <span><%= f.text_field :body, placeholder: "Enter one word tag here." %><%= f.text_field :body, placeholder: "Enter one word tag here." %><%= f.text_field :body, placeholder: "Enter one word tag here." %></span>
    </div>
  <% end %>
<% end %>

app/views/posts/show.html.erb
<h3>random qwap</h3>

<h5><%= post.body %>
  <div class="post user name">
    <%= link_to post.user.name, post.user if post.user %>, <%= time_ago_in_words(post.created_at) %> ago,
  </div>
  <div class="votes total">
    [<%= pluralize(post.up_votes, 'up vote') %>/<%= pluralize(post.down_votes, 'down vote') %>]
  </div>

  <div class="fav">
    <%= render partial: 'favorites/favorite', locals: { post: post } %>
  </div>

  <% if current_user %>
  <div class="tweet">
    <a href="https://twitter.com/share" class="basic ui button" data-lang="en">Tweet</a>
  </div>

  <% else %>

  <div class="tweet pull left">
    <a href="https://twitter.com/share" class="basic ui button" data-lang="en">Tweet</a>
  </div>
  <% end %>

  </h5>