config/routes.rb
Rails.application.routes.draw do

resources :posts do
  collection do
    get '/newest' => 'posts#newest', as: :newest
    get '/oldest' => 'posts#oldest', as: :oldest
    get '/best' => 'posts#best', as: :best
    get '/worst' => 'posts#worst', as: :worst
  end
  resources :comments
    resources :tags
    get '/up-vote' => 'votes#up_vote', as: :up_vote
    get '/down-vote' => 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
end

resources :catagories

resources :relationships, only: [:create, :destroy]

  devise_for :users
  resources :users, only: [:show, :index, :update] do
      member do
        get :following, :followers
      end
  end

  get 'home' => 'welcome#index'

  root to: 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }

  after_save :update_post

   def up_vote?
    value == 1
  end

  def down_vote?
    value == -1
  end

  private

  def update_post
    self.post.update_rank
  end



end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :setup

  def up_vote
    update_vote(1)
    redirect_to :back
  end

  def down_vote
    update_vote(-1)
    redirect_to :back
  end

    private

  def setup
    
    @post = Post.find(params[:post_id])

    @vote = @post.votes.where(user_id: current_user.id).first
  end

    def update_vote(new_value)
    if @vote # if it exists, update it
      authorize @vote, :update?
      @vote.update_attribute(:value, new_value)
    else # create it
      @vote = current_user.votes.create(value: new_value, post: @post)
      authorize @vote, :create?
      @vote.save
    end
  end
end

app/views/votes/_voter.html.erb
<% if policy( Vote.new ).create? %>
  <div>
    <div class="up">
      <%= link_to post_up_vote_path(post) do %>
      <i class="red triangle up icon "></i>
      <% end %>
    </div>

    <div class="points">
      <small><%= pluralize(post.points, '') %></small>
    </div>
 
      <div class="down">
        <%= link_to post_down_vote_path(post) do %>
        <i class="red triangle down icon "></i>
        <% end %>
      </div>
  </div>
<% else %>
  <div>
    <div class="up">
      <%= link_to new_user_session_path do %>
      <i class="red triangle up icon "></i>
      <% end %>
    </div>

    <div class="points">
      <small><%= pluralize(post.points, '') %></small>
    </div>
 
      <div class="down">
        <%= link_to new_user_session_path do %>
        <i class="red triangle down icon "></i>
        <% end %>
      </div>
  </div>
<% end %>