config/routes.rb
Rails.application.routes.draw do

resources :posts do
  collection do
    get '/newest' => 'posts#newest', as: :newest
    get '/oldest' => 'posts#oldest', as: :oldest
    get '/best' => 'posts#best', as: :best
    get '/worst' => 'posts#worst', as: :worst
  end
  resources :comments
    resources :tags
    get '/up-vote' => 'votes#up_vote', as: :up_vote
    get '/down-vote' => 'votes#down_vote', as: :down_vote
      resources :favorites, only: [:create, :destroy]
end

resources :catagories

resources :relationships, only: [:create, :destroy]

  devise_for :users
  resources :users, only: [:show, :index, :update] do
      member do
        get :following, :followers
      end
  end

  get 'home' => 'welcome#index'

  root to: 'welcome#index'

  get 'about' => 'welcome#about'

end

app/models/catagory.rb
class Catagory < ActiveRecord::Base
  
  has_many :posts

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  default_scope { order('updated_at DESC') }

  validates :body, length: { minimum: 1, maximum: 300 }, presence: true
  validates :post, presence: true
  validates :user, presence: true

after_create :send_favorite_emails

  private

  def send_favorite_emails
    self.post.favorites.each do |favorite|
      FavoriteMailer.new_comment(favorite.user, self.post, self).deliver
    end
  end


end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  #has_many :tags, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  # belongs_to :catagory

  after_create :send_followers_email

  def up_votes
    self.votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  def points
    self.votes.sum(:value).to_i
  end

  def update_rank
    #age = (self.created_at - Time.new(1970,1,1)) / 86400
    new_rank = points #+ age

    self.update_attribute(:rank, new_rank)
  end

  validates :body, length: { minimum: 1, maximum: 200 }, presence: true
  validates :user, presence: true

  private 

  def create_vote
    user.votes.create(value: 1, post: self)
  end

  #def send_email_followers
    # grab the creator of the post (post.user)
    #@post.user =  
    # see if they have any followers
    # if so, send an email to each follower
  #end

  def send_followers_email
    relationships = Relationship.where(followed_id: self.user.id)
    relationships.each do |relationship|
      FollowMailer.new_post(relationship.follower, self).deliver
    end
  end

# When someone votes in the top 25 index view the qwap only earns 1/4 pt
#def create_top_vote
  #user.votes.create(value: 0.25, post: self)
#end

# When someone votes in the random qwap mode, the qwap earns 2pts
#def create_random_vote
  #user.votes.create(value: 2, post: self)
#end

# When someone votes in the member qwap view, the qwap earns 1/2 pt
#def create_member_vote
  #user.votes.create(value: 0.5, post: self)
#end

# Users get points for voting

# Users can only vote 10 times per 24hrs (?)

# When someone votes in the top 25 index view the user earns 1/4 pt
#def create_top_vote
  #user.votes.create(value: 0.25, user: self)
#end

# When someone votes in the random qwap mode, the user earns 2pts
#def create_random_vote
  #user.votes.create(value: 2, user: self)
#end

# When someone votes in the member qwap view, the user earns 1/2 pt
#def create_member_vote
  #user.votes.create(value: 0.5, user: self)
#end








end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :post
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :posts, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
                                    class_name: "Relationship",
                                    dependent: :destroy
  has_many :followers, through: :reverse_relationships, source: :follower

# def self.top_rated
#   self.select('users.*'). # Select all attributes of the user
#   select('COUNT(DISTINCT comments.id) AS comments_count'). # Count the comments made by the user
#   select('COUNT(DISTINCT posts.id) AS posts_count'). # Count the posts made by the user
#   select('COUNT(DISTINCT comments.id) + COUNT(DISTINCT posts.id) AS rank'). # Add the comment count to the post count and label the sum as "rank"
#   joins(:posts). # Ties the posts table to the users table, via the user_id
#   joins(:comments). # Ties the comments table to the users table, via the user_id
#   group('users.id'). # Instructs the database to group the results so that each user will be returned in a distinct row
#   order('rank DESC') # Instructs the database to order the results in descending order, by the rank that we created in this query. (rank = comment count + post count)
# end

def role?(base_role)
  role == base_role.to_s
end

def favorited(post)
  # what is this doing?
  self.favorites.where(post_id: post.id).first
end

def voted(post)
  self.votes.where(post_id: post.id).first
end


def following?(other_user)
  relationships.find_by(followed_id: other_user.id)
end 

def follow!(other_user)
  relationships.create!(followed_id: other_user.id)
end

def unfollow!(other_user)
  relationships.find_by(followed_id: other_user.id).destroy
end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote." }

  after_save :update_post

   def up_vote?
    value == 1
  end

  def down_vote?
    value == -1
  end

  private

  def update_post
    self.post.update_rank
  end



end

app/controllers/admin.rb
#Admin::PostsController

#  namespace :admin do
 #   resources :posts, :tags, :comments
 # end
#end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new

  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'form-group has-error'
    else
      content_tag :div, capture(&block), class: 'form-group'
    end
  end

  def current_user?(user)
    user == current_user
  end
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>qwapper</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <%= link_to home_path do %> 
    <img><%= image_tag 'quacker.png' %></img>
    <% end %>

    <%= link_to "qwap", posts_path, class: "basic ui button" %> 
    <%= link_to "qwappers", users_path, class: "basic ui button" %> 

    <% if current_user %>
      <%= link_to (current_user.name || current_user.email), current_user, class: 'basic ui button' %>
      <%= link_to edit_user_registration_path, class: 'basic ui icon button pull right' do %>
        <i class="bullseye icon"></i>
        <% end %>
      <%= link_to "log out", destroy_user_session_path, method: :delete, class: "basic ui button" %> 
    <% else %>
      <%= link_to "sign in", new_user_session_path, class: "basic ui button" %> 
      <%= link_to "sign up", new_user_registration_path, class: "basic ui button" %> 
    <% end %>

  </header>

    
  <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>


<%= yield %>


 <footer1>
 <div class="ui horizontal list">
  <div class="item">
    <footer><%= link_to "qwaps by type /", posts_path %></footer>
  </div>
  <div class="item">
   <footer><%= link_to "philosophy of qwap /", about_path %></footer>
  </div>
  <div class="item">
    <footer><%= link_to "sign up /", new_user_registration_path %></footer> 
  </div>
  <div class="item">
    <footer><%= link_to "© qwapper LLC 2014", home_path %></footer>
  </div>
</div>
</footer1>







</body>
</html>